context:
  version: "0.2.2"
  python_min: "3.11"

package:
  name: chatom
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/chatom/chatom-${{ version }}.tar.gz
  sha256: 5103c010865951da522c37dac7e2e72bb0ec85dee02f4f4aaf20072299e158bb

build:
  script: python -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - mistune >=3
    - pydantic >=2
    - singledispatch

tests:
  - python:
      imports:
        - chatom
        - chatom.base
        - chatom.format
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/1kbgz/chatom
  summary: 'Minimum viable chat components'
  description: |
    Framework-agnostic chat application models and utilities
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://github.com/1kbgz/chatom
  repository: https://github.com/1kbgz/chatom

extra:
  recipe-maintainers:
    - timkpaine
